export default {
    MARK_NOTIFICATIONS_AS_READ_BY_ID:"MARK_NOTIFICATIONS_AS_READ_BY_ID",
    MAEK_ALL_NOTIFICATIONS_AS_READ:"MAEK_ALL_NOTIFICATIONS_AS_READ",
    START_MARK_AS_READ:"START_MARK_AS_READ",
    FINISH_MARK_AS_READ:"FINISH_MARK_AS_READ",
    RECEVIED_NOTIFICATIONS:"RECEVIED_NOTIFICATIONS",
    START_LOGIN:"START_LOGIN",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED:"LOGIN_FAILED",
    CHANGE_AVATOR:"CHANGE_AVATOR"
}
